name: CD pipeline to Azure Web App - autopile

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: autopile
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore
        run: dotnet restore ./AutoPile.sln

      - name: Build
        run: dotnet build ./AutoPile.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./AutoPile.sln --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        
      - name: Deployment
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
      

    
  
          
