name: AutoPile CI/CD Pipeline
on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: autopile
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Restore
        run: dotnet restore ./AutoPile.sln
        
      - name: Build
        run: dotnet build ./AutoPile.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-build --configuration Release
        
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: dotnet publish ./AutoPile.sln --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        
      - name: Upload Artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  cd:
    name: Deploy to Azure
    needs: ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"

