name: Build and deploy ASP.Net Core app to Azure Web App - autopile

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore
        run: dotnet restore ./AutoPile.sln

      - name: Build
        run: dotnet build ./AutoPile.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Release

    
  
          
